/*
 * REVISION ATLAS - INSTRUCTOR COURSE CODE (COMMENTS ADDED ONLY)
 * Section 05: AXI-Lite Single Beat without Pipeline
 * Lecture path: Lessons 68-72 - AXI-Lite Protocol-Checker Exercise
 * Downloadable source page: Lesson 072
 * Module: p_axi_tb
 * Role: Instructor-supplied testbench/stimulus
 *
 * PRESERVATION:
 * - Module/signal names, executable statements, FSM architecture, and stimulus
 *   are retained. Only comments and one-module-per-file organization were added.
 *
 * ASSUMPTIONS:
 * - The design pair exercises the write-only teaching subset.
 * - A Vivado AXI Protocol Checker/block-design wrapper is external to these files.
 * - One transaction is stimulated at a time.
 *
 * USED / OMITTED / SIMPLIFIED:
 * - No replacement checker, assertion library, read path, or pipeline is added.
 * - The referenced design_1_wrapper is generated by Vivado and is not supplied on the lesson page.
 *
 * BEHAVIORAL CONSEQUENCE:
 * - Checker observations match the lecture because the RTL is preserved.
 * - Lesson 72 ends without endmodule on the course page; that incomplete ending is retained and reported by compilation.
 *
 * SOURCE INTEGRITY NOTE:
 * - The instructor page ends this module without `endmodule`; it is preserved
 *   exactly so verification reports the missing terminator instead of hiding it.
 */
`timescale 1ns / 1ps

module p_axi_tb;

// Signal definition - clk: rising-edge clock for the retained FSM and handshakes.
reg clk = 0;
// Signal definition - resetn: active-LOW reset for the course state/output logic.
reg resetn = 0;
// Signal definition - wr: operation selector; HIGH chooses write and LOW chooses read.
reg wr;
// Signal definition - din: local write/payload data supplied to the manager.
reg [31:0] din;
// Signal definition - strbin: byte-lane strobe associated with the write payload.
reg [3:0]  strbin;
// Signal definition - addrin: local command address driven by the testbench into the course manager.
reg [31:0] addrin;

// Signal definition - pc_asserted: vector of assertion bits reported by the external AXI Protocol Checker.
wire [159:0] pc_asserted;
// Signal definition - pc_status: summary status returned by the external AXI Protocol Checker.
wire pc_status;
// Signal definition - i: loop index used by initialization or TB stimulus.
integer i = 0;
// Signal definition - bvalid: AXI write-response VALID.
wire bvalid;

design_1_wrapper DUT(
    .i_addrin(addrin),
    .i_din(din),
    .i_strb(strbin),
    .i_wr(wr),
    .m_axi_aclk(clk),
    .m_axi_aresetn(resetn),
    .pc_asserted(pc_asserted),
    .pc_status(pc_status),
    .s_axi_bvalid(bvalid)
);


always #10 clk = ~clk;

initial begin
resetn = 0;
repeat(2)@(posedge clk);
resetn = 1;
end

initial
begin
@(posedge resetn);
@(posedge clk);

for( i = 0; i < 10; i = i+1)
begin
@(posedge clk);
wr = 1'b1;
addrin  = $urandom_range(0,20);
din     = $urandom_range(1,10);
strbin  = 4'b1111;
@(posedge bvalid);
wr = 1'b0;
@(posedge clk);
end
 $stop;
end
