/*
 * REVISION ATLAS - INSTRUCTOR COURSE CODE (COMMENTS ADDED ONLY)
 * Section 05: AXI-Lite Single Beat without Pipeline
 * Lecture path: Lessons 68-72 - AXI-Lite Protocol-Checker Exercise
 * Downloadable source page: Lesson 071
 * Module: p_m_axi
 * Role: Instructor design RTL
 *
 * PRESERVATION:
 * - Module/signal names, executable statements, FSM architecture, and stimulus
 *   are retained. Only comments and one-module-per-file organization were added.
 *
 * ASSUMPTIONS:
 * - The design pair exercises the write-only teaching subset.
 * - A Vivado AXI Protocol Checker/block-design wrapper is external to these files.
 * - One transaction is stimulated at a time.
 *
 * USED / OMITTED / SIMPLIFIED:
 * - No replacement checker, assertion library, read path, or pipeline is added.
 * - The referenced design_1_wrapper is generated by Vivado and is not supplied on the lesson page.
 * - BRESP is present but ignored; BVALID alone marks write completion.
 *
 * BEHAVIORAL CONSEQUENCE:
 * - Checker observations match the lecture because the RTL is preserved.
 * - A subordinate error response is not reported to the local interface.
 * - Lesson 72 ends without endmodule on the course page; that incomplete ending is retained and reported by compilation.
 */
`timescale 1ns / 1ps


module p_m_axi(
		// Signal definition - m_axi_aclk: rising-edge clock for the retained FSM and handshakes.
		// Signal definition - m_axi_aresetn: active-LOW reset for the course state/output logic.
		input	wire			m_axi_aclk, m_axi_aresetn,

		// Signal definition - i_wr: local operation control; asserted starts writes in write lessons, while deasserted selects reads in the read-only lesson.
		input	wire			i_wr,
		// Signal definition - i_din: local write payload loaded into the AXI write-data channel when a write is requested.
		input	wire	[31:0]	i_din,
		// Signal definition - i_strb: byte-lane strobe associated with the write payload.
		input wire [3:0] i_strb,
		// Signal definition - i_addrin: local command address loaded into the manager's AXI address channel.
		input wire [31:0] i_addrin,

///////////////Write Address Channel
		// Signal definition - m_axi_awvalid: AXI write-address VALID.
		output	reg			 m_axi_awvalid,
		// Signal definition - m_axi_awready: AXI write-address READY.
		input	wire			m_axi_awready,
		// Signal definition - m_axi_awaddr: AXI write address offered with AWVALID.
		output	reg	 [31:0] m_axi_awaddr,
//////////////Write Data Channel
		// Signal definition - m_axi_wvalid: AXI write-data VALID.
		output	reg			 m_axi_wvalid,
		// Signal definition - m_axi_wready: AXI write-data READY.
		input	wire			m_axi_wready,
		// Signal definition - m_axi_wdata: AXI write payload.
		output	reg	 [31:0]	m_axi_wdata,
		// Signal definition - m_axi_wstrb: AXI write byte-lane strobes.
		output	reg [3:0]	m_axi_wstrb,
////////////Write Response Channel
		// Signal definition - m_axi_bvalid: AXI write-response VALID.
		input	wire			m_axi_bvalid,
		// Signal definition - m_axi_bready: AXI write-response READY.
		output	reg			 m_axi_bready,
		// Signal definition - m_axi_bresp: AXI write-response status input; the course master ignores it and treats BVALID as completion.
		input	wire	[1:0]	m_axi_bresp
 );

///Write Opeartion


initial m_axi_awvalid = 0;
initial m_axi_wvalid = 0;
initial m_axi_bready = 0;

always@(posedge m_axi_aclk)
begin
 if(m_axi_aresetn == 1'b0)
 begin
 m_axi_awvalid <= 0;
 m_axi_wvalid <= 0;
 m_axi_bready <= 0;
 end
 else if (m_axi_bready)
 begin
 if(m_axi_awready)
 m_axi_awvalid <= 0;

 if(m_axi_wready)
 m_axi_wvalid <= 0;

 if(m_axi_bvalid)
 m_axi_bready <= 0;

 end
 else if(i_wr)
 begin
 m_axi_awvalid <= 1;
 m_axi_wvalid <= 1;
 m_axi_bready <= 1;

 end

end
////// Write Data

initial m_axi_awaddr = 0;

always@(posedge m_axi_aclk)
begin
 if(m_axi_aresetn == 1'b0)
 m_axi_awaddr <= 0;
 else if (i_wr)
 m_axi_awaddr <= i_addrin;
 else if (m_axi_awvalid && m_axi_awready )
 m_axi_awaddr <= 0;
end

///////

initial m_axi_wdata = 0;
initial m_axi_wstrb = 0;

always@(posedge m_axi_aclk)
begin
 if(m_axi_aresetn == 1'b0)
 begin
 m_axi_wdata <= 0;
 m_axi_wstrb <= 0;
 end
 else if (i_wr)
 begin
 m_axi_wdata <= i_din;
 m_axi_wstrb <= i_strb;
 end
 else if (m_axi_wvalid && m_axi_wready )
 begin
 m_axi_wdata <= 0;
 m_axi_wstrb <= 0;
 end
end


endmodule
